name: Feature Request
description: New feature suggestion for the editor
labels: [enhancement]
body:
  - id: validation
    type: checkboxes
    attributes:
      label: Before opening this issue, I ensure that...
      options:
      - label: I have checked **both open and closed** issues and confirmed this feature has not already been requested.
        required: true
      - label: I acknowledge the addition of this feature is neither guaranteed nor a priority.
        required: true
      - label: This request is not related to any unofficial forks of the editor, and any requests related to those should be kept in the appropriate repository.
        required: true
  - id: editortool
    type: dropdown
    validations:
      required: true
    attributes:
      label: "Editor Tool"
      description: For which tool is this feature request for?
      multiple: false
      options:
        - Scene Editor
        - Animation Editor
        - GameConfig Editor
        - Palette Editor
        - RSDK Unpacker
        - Model Manager
        - Script Compiler
        - GFX Manager
        - UserDB Manager
        - RSV Manager
        - Other
  - id: feature
    type: textarea
    validations:
      required: true
    attributes:
      label: Requested Feature
      description: What new feature do you want to see on the editor?
  - id: comments
    type: textarea
    validations:
      required: false
    attributes:
      label: Additional Comments
      description: Provide any additional information if needed.
